package com.example.pethood.data

import java.util.Date

/**
 * Data class representing a pet that is put up for adoption
 */
data class AdoptionPet(
    val id: String = "", //should be autogenerated by firebase
    val name: String = "",
    val category: String = "", // "Cat", "Dog", or "Bird"
    val type: String = "", // Breed or specific type
    val location: String = "",
    val description: String = "",
    val contactNumber: String = "",
    val petId: String = "", //pet added to the app
    val userId: String = "", // ID of the user who put the pet up for adoption
    val date: Date = Date(),
    val imageUri: String = "" // URI of the pet's image
)